### ISSUE TITLE
kml data bug cant delete files/load them

### ISSUE THREAD

**Issue by wizord-gaming** [wizord-gaming/TuriteaWebResources#30]
when uploading the turitea kml files in the /data/kml they get added to the folder /resources/kml

and when I call  /api/listKML i get

["Turitea Pitfall Points (1).kml", "Turitea Pitfall Points.kml", "Turitea.kml"]

but when I try to load or delete the files with the following URLs

http://localhost/api/deleteKML&name=Turitea%20Pitfall%20Points%20(1).kml
http://localhost/api/getKML&name=Turitea%20Pitfall%20Points%20(1).kml 

it just gives me a 404 error

**Comment by ChenXingYuChina** [comment]
the url is wrong, should use ? to replace &
