### ISSUE TITLE
about spead up pin system

### ISSUE THREAD

**Issue by ChenXingYuChina** [wizord-gaming/TuriteaWebResources#35]
If you need to optimize the performance of the pin system, please minimize the number of Entity in the system. Js itself is not suitable for processing large amounts of data. Minimizing the size of the data can optimize the overall performance. If you are willing to consider optimization, please optimize according to the following ideas. Reasonable judgment of the circumstances in which no request to the server is required. Because the root cause of the overall performance bottleneck is the large amount of html formatted text in the pin object, reducing the number of requests can effectively optimize the system. Simply reducing the number of replacements of the EntityCollection does not solve it, and it will cause bug, delay to show when delete.

**Comment by wizord-gaming** [comment]
but removing and adding all of the pins with every map update requires a lot more CPU cycles compared to just checking if the pin is already there. then not adding it, this also means if you zoom in on a pin or move the camera at all the pins get deselected this isnt very good for a user thats why I did it, in terms of optimizing the map the pins that are not on screen are not drawn why would they cause much issue the scene graph for the map will just get rid of them by its self, however requiring to add them and remove every map update adds far more cpu overhead compared to the gpu overhead of just leaving them.

**Comment by ChenXingYuChina** [comment]
First of all, you judge that the id of all the points in the system does not save the complexity of the CPU time. The current time complexity is O(n^2) and n is constantly rising. Of course, if the map is replaced by O(n), delete Reconstruction round is O(n). Now it's very likely that your code will time out. There is a thousand points in the imported csv file. n^2 is interested in the calculator. You can try to track down. When there are many points, the network overhead should be much longer than the js running time. So the system bottleneck is the speed of network transmission, not the mapping and point set changes. The number of points in your EntityCollection will be more and more. It will sometimes be more expensive to judge a circle than to change one round. If you think that adding an entity object is expensive, please choose to create an object pool. If you have this Ability. Moreover, when exploring, it may be deeply deep into a certain area. The points in the visible area of ​​the user will generally be fixed values. Otherwise, the points will be too dense and cannot be correctly selected. The user will naturally try to zoom in. The rest of the rest of the points are useless, and the user drags the event much more slowly than you think. You can try it and see the console output. Moreover, each process will be redrawn, all points will be drawn, and then the useful part will be intercepted, there is no optimization for performance. Moreover, not to mention, when other users change, the design that is not deleted can not meet the real-time nature. Moreover, in the back-end design, the id of the deleted point will be recycled, and will be reused after about one hundred increments. When a researcher imports a csv file, the number of points inside it is likely to exceed this value, which may cause a bug. If you want to improve, please calculate the area that does not need to be reloaded, and do not directly enter the request process. There are a lot of html in your pin's description. Keeping them in memory or in the database is not a good method at all. It is good to reduce the overhead of this part. Not all devices have enough memory to run such programs. The effective optimization process of this system is much more complicated than what I am talking about now. The individual optimization is not necessarily effective. It is likely to be negative optimization. If it is mid-term, I will support you to optimize, for example. Using MD5 to determine whether the point has been modified, or the joint backend for state query, my backend cache has long supported checking for updates, and so on to reduce its network process and front-end process. But now is the end of the project, reducing the slight optimization of the effect, it will be more effective to beautify the appearance at this time. The intrinsic optimization of these features is not as good as the performance of string addition loss, or the loss of accessing html from the database. Do some optimizations that are obvious and effective, and that are within your power.

**Comment by ChenXingYuChina** [comment]
Why is the network a bottleneck? You are now accessing the machine, just a network card, even if it is only placed in the LAN, the network transmission speed will be very obvious.

**Comment by wizord-gaming** [comment]
how do you suggest we fix the unselecting issue?
and for complexity, I can get it down to O(m*log(n)) quickly and easily, m being the pins that just go sent and n being the pins already drawn.

**Comment by ChenXingYuChina** [comment]
"how do you suggest we fix the unselecting issue?" what it means.
That can go to O(m) if you use map.

**Comment by ChenXingYuChina** [comment]
Optimizing speed is a system problem, and your optimization is not enough. Now it is negative optimization.

**Comment by wizord-gaming** [comment]
https://youtu.be/aKsWWQ4CqVk

when you zoom in or use the camera button the pins reload and the pin you had selected deselects its self. its why I made that change, to begin with I know it made it a little slower it was there to stop the pins unselecting, now there are a few ways to fix it I can just call for areas that havent been called and keep list of blocks that have been called that shouldn't be too hard however may take a while to implement, or I can change the list to a treeset and binary search each time resulting in the O(n*log(m)), but that was there as a bug fix ask before just removing code like that.

**Comment by wizord-gaming** [comment]
upon further thought, I could use a hash map then it would be o(1) time for each check to see if it's on the map resulting in an O(n) time for each map update.

**Comment by ChenXingYuChina** [comment]
First of all, I don't think this is a problem, because the enlarged maps are almost all mosaics, and this is not in line with the normal user's use, which is an invalid result of excessive trials. Of course, if you want to change, please change the following way, choose to use the object pool to buffer the remaining entity object of the useless pin, and control the size of the object pool, automatically plan the size of the object pool according to the memory of the host, if you do not want to delete the pin, then Consider what timing should be used to clear the point. All the information of the point is already built as html load when cesium loads its description. Such an object has many attributes, which take up a lot of memory and is not suitable for saving too much. The method is solved. And by recording the areas that have been accessed, calculate the timing at which the server should be requested to update, to minimize the request to the server, and set the duration or timing to refresh the data to achieve real-time effects, when the pin id What should be done when repeating but not the same object, and how to deal with when it needs to be updated, how to deal with it when deleting, etc. Of course, I don't recommend you to do this because it is a waste of time. It is not something that should be done now. We should pay more attention to the presentation of next week.

**Comment by wizord-gaming** [comment]
![image](https://user-images.githubusercontent.com/13291118/66382369-9404ca00-ea17-11e9-8e3e-02bde1adb849.png)
it uses less ram with 1000+ pins than running a youtube video something that a lot
 of people have running in the background 
![image](https://user-images.githubusercontent.com/13291118/66382841-6409f680-ea18-11e9-9783-f05c943af12e.png)
and it doesn't take that long to check each one even with n^2 time

**Comment by ChenXingYuChina** [comment]
so It's not a bottleneck, the bottleneck is net

**Comment by ChenXingYuChina** [comment]
I have wrote serval problems in above, let your solution meet everyone.

**Comment by wizord-gaming** [comment]
using HashSet so O(n) time if you wish to do it your way feel free too, however, I suggest working on the report instead.
