### ISSUE TITLE
about Regression Testing

### ISSUE THREAD

**Issue by ChenXingYuChina** [wizord-gaming/TuriteaWebResources#36]
Please perform regression test after each change. If there is any function that does not work properly, please do not submit.

**Comment by wizord-gaming** [comment]
what commit are you referring to ?

**Comment by ChenXingYuChina** [comment]
Please remember that this is not your own git library, but put in your name for the moment, because you are the team leader. Originally, this library should be under a newly created user, and you have no right to close the permission of opening issue of others.
I open this question not to hold anyone accountable, but to warn everyone that now we are changing the same parts, instead of doing it separately as before, your submission will affect the normal work of others.
Your current behavior is obviously beyond the normal team leader's authority, and you are abusing your rights as the library owner.

**Comment by ChenXingYuChina** [comment]
wizord-gaming locked as resolved and limited conversation to collaborators 29 minutes ago

**Comment by ChenXingYuChina** [comment]
Please remember that this is not your own git library, but put in your name for the moment, because you are the team leader. Originally, this library should be under a newly created user, and you have no right to close the permission of opening issue of others.
I open this question not to hold anyone accountable, but to warn everyone that now we are changing the same parts, instead of doing it separately as before, your submission will affect the normal work of others.
Your current behavior is obviously beyond the normal team leader's authority, and you are abusing your rights as the library owner.

**Comment by wizord-gaming** [comment]
I closed it bc its not an issue, there is no fix, this should have just been a message not an issue.
