### ISSUE TITLE
why are we keeping user location?

### ISSUE THREAD

**Issue by wizord-gaming** [wizord-gaming/TuriteaWebResources#37]
why are we keeping user location I think it should start on the Turitea,

starting where you left off is kinda stupid, imagine going to a cafe website and there map not starting on where the cafe is it doesn't make sense.

**Comment by ChenXingYuChina** [comment]
if you are a researcher you change or create one pin, if it don't remember the location, it will difficult to find it.

**Comment by wizord-gaming** [comment]
but if a researcher is looking for a pin he would have had it a while ago not had just looked at it so it wouldn't really help. all it would do is when someone comes back to it will not center on the Turitea.

**Comment by ChenXingYuChina** [comment]
if you like please make a home button

**Comment by ChenXingYuChina** [comment]
But I believe anyone will like remebering the position. remeber that it is a explore system, no one want to restart.

**Comment by ChenXingYuChina** [comment]
it just a very little thing in this project if you like please add, but don't delete this function. Both you and me are not all the users.
