### ISSUE TITLE
HTML file error

### ISSUE THREAD

**Issue by nzwlagr** [wizord-gaming/TuriteaWebResources#40]
The HTML editor for the 'home.html' page is reporting an error in the footer element. It is saying it doesn't like the name="foot" field. While the page is working, it would be better that we make a submission without errors.
Can this be removed? For that matter, do we need the class="slow" and id="foot" fields either.

This should be an easy fix.

**Comment by ChenXingYuChina** [comment]
I had fix it in the last submit, and Slow is to make these parts appear at the same time
